import pygame

pygame.init()

# --- SCREEN INFORMATION ---

#get computer info
info = pygame.display.Info()

COMPUTER_WIDTH = info.current_w
COMPUTER_HEIGHT = info.current_h

#screen width/height
SCREEN_WIDTH = COMPUTER_WIDTH
SCREEN_HEIGHT = COMPUTER_HEIGHT

#alt width/height (For dynamic sizing testing)
#SCREEN_WIDTH = 720
#SCREEN_HEIGHT = 500


# --- BOARD DIMENSIONS ---
BOARD_WIDTH = SCREEN_HEIGHT * 0.856627592
BOARD_HEIGHT = SCREEN_HEIGHT * 0.856627592

NUM_CELLS = 40


# --- DICE DISPLAY INFORMATION ---

#width/height
DICE_WIDTH = SCREEN_HEIGHT * 0.0450856628
DICE_HEIGHT = DICE_WIDTH

#dice set display width/height
TOTAL_DICE_WIDTH = DICE_WIDTH * 2 + 15
TOTAL_DICE_HEIGHT = DICE_HEIGHT

#gap between dice in set
DIE_GAP = SCREEN_HEIGHT * 0.0135256988277728

#coords (x,y) for both die
DICE_X1 = SCREEN_WIDTH // 2 - TOTAL_DICE_WIDTH // 2
DICE_Y1 = SCREEN_HEIGHT // 1.4 - TOTAL_DICE_HEIGHT // 2
DICE_X2 = DICE_X1 + DICE_WIDTH + 15
DICE_Y2 = DICE_Y1

#Lower and upper random range for amount of side changes (rolls)
ROLL_RANGEL = 15
ROLL_RANGEH = 35



# --- STARTUP WINDOW DISPLAY INFORMATION ---

# background
START_WIN_WIDTH = SCREEN_WIDTH * 0.5
START_WIN_HEIGHT = SCREEN_HEIGHT * 0.5
START_WIN_X = SCREEN_WIDTH // 2 - START_WIN_WIDTH // 2
START_WIN_Y = SCREEN_HEIGHT // 2 - START_WIN_HEIGHT // 2

# startup window title
START_WIN_TITLE_X = SCREEN_WIDTH * 0.5
START_WIN_TITLE_Y = SCREEN_HEIGHT * 0.3

# close button
CLOSE_BTN_WIDTH = SCREEN_WIDTH * 0.08
CLOSE_BTN_HEIGHT = SCREEN_HEIGHT * 0.05
CLOSE_BTN_X = SCREEN_WIDTH * 0.7
CLOSE_BTN_Y = SCREEN_HEIGHT * 0.7

# add player button
ADD_PLAYER_BTN_WIDTH = SCREEN_WIDTH * 0.1
ADD_PLAYER_BTN_HEIGHT = SCREEN_HEIGHT * 0.05
ADD_PLAYER_BTN_X = SCREEN_WIDTH * 0.5
ADD_PLAYER_BTN_Y = SCREEN_HEIGHT * 0.6

# name label
NAME_LABEL_X = SCREEN_WIDTH * 0.5
NAME_LABEL_Y = SCREEN_HEIGHT * 0.385

# name input box
NAME_INPUT_WIDTH = SCREEN_WIDTH * 0.1
NAME_INPUT_HEIGHT = SCREEN_HEIGHT * 0.03
NAME_INPUT_X = SCREEN_WIDTH * 0.5 - NAME_INPUT_WIDTH // 2
NAME_INPUT_Y = SCREEN_HEIGHT * 0.4

# piece selection icon dimensions
ST_PIECE_WIDTH = SCREEN_HEIGHT * 0.05
ST_PIECE_HEIGHT = ST_PIECE_WIDTH

ST_PIECE_X = SCREEN_WIDTH * 0.5
ST_PIECE_Y = SCREEN_HEIGHT * 0.5

ST_PIECE_OFFSET = SCREEN_WIDTH * 0.03


# --- PLAYER PIECE DISPLAY INFORMATION ---

PIECE_WIDTH = SCREEN_WIDTH * 0.02
PIECE_HEIGHT = PIECE_WIDTH

# --- BUY SCREEN DISPLAY INFORMATION ---

# window
BUY_WIN_X = SCREEN_WIDTH * 0.35
BUY_WIN_Y = SCREEN_HEIGHT * 0.2
BUY_WIN_WIDTH = SCREEN_WIDTH * .3
BUY_WIN_HEIGHT = SCREEN_WIDTH * .4

# property name
PROP_NAME_X = SCREEN_WIDTH * 0.5
PROP_NAME_Y = SCREEN_HEIGHT * 0.25

# name underline
NAME_LN_START = (SCREEN_WIDTH * 0.43, SCREEN_HEIGHT * 0.28)
NAME_LN_END = (SCREEN_WIDTH * 0.57, SCREEN_HEIGHT * 0.28)

# price
BUY_PRICE_X = SCREEN_WIDTH * 0.5
BUY_PRICE_Y = SCREEN_HEIGHT * 0.35

# --- RAILROAD BUY INFORMATION ---

# railroad price
RAIL_BUY_PRICE_X = SCREEN_WIDTH * 0.5
RAIL_BUY_PRICE_Y = SCREEN_HEIGHT * 0.48

# railroad img
RAIL_IMG_WIDTH = SCREEN_WIDTH * 0.075
RAIL_IMG_HEIGHT = SCREEN_HEIGHT * 0.075
RAIL_IMG_X = SCREEN_WIDTH * 0.5
RAIL_IMG_Y = SCREEN_HEIGHT * 0.37

# railroad img SML
RAIL_IMG_WIDTH_SML = SCREEN_WIDTH * 0.045
RAIL_IMG_HEIGHT_SML = SCREEN_HEIGHT * 0.045
RAIL_IMG_SML_X = SCREEN_WIDTH * 0.6
RAIL_IMG_SML_Y = SCREEN_HEIGHT * 0.45

# --- UTILITY BUY INFORMATION ---

# util Img
UTIL_IMG_WIDTH = SCREEN_WIDTH * 0.1
UTIL_IMG_HEIGHT = SCREEN_HEIGHT * 0.1
UTIL_IMG_X = SCREEN_WIDTH * 0.5
UTIL_IMG_Y = SCREEN_HEIGHT * 0.37

# util Img SML
UTIL_IMG_WIDTH_SML = SCREEN_WIDTH * 0.075
UTIL_IMG_HEIGHT_SML = SCREEN_HEIGHT * 0.075
UTIL_IMG_SML_X = SCREEN_WIDTH * 0.6
UTIL_IMG_SML_Y = SCREEN_HEIGHT * 0.45

# --- TAX INFORMATION ---

# income tax
INCOME_TAX_X = SCREEN_WIDTH * 0.5
INCOME_TAX_Y = SCREEN_HEIGHT * 0.45
INCOME_TAX_WIDTH = SCREEN_WIDTH * 0.03
INCOME_TAX_HEIGHT = SCREEN_HEIGHT * 0.03

LUXURY_TAX_WIDTH = SCREEN_WIDTH * 0.1
LUXURY_TAX_HEIGHT = SCREEN_HEIGHT * 0.18

TAX_TXT_X = SCREEN_WIDTH * 0.5
TAX_TXT_Y = SCREEN_HEIGHT * 0.6

# --- FREE PARKING AND GO TO JAIL INFORMATION ---

# free parking
FREE_PARKING_X = SCREEN_WIDTH * 0.5
FREE_PARKING_Y = SCREEN_HEIGHT * 0.4
FREE_PARKING_WIDTH = SCREEN_WIDTH * 0.1
FREE_PARKING_HEIGHT = SCREEN_HEIGHT * 0.14

# go to jail
GO_TO_JAIL_X = SCREEN_WIDTH * 0.5
GO_TO_JAIL_Y = SCREEN_HEIGHT * 0.43
GO_TO_JAIL_WIDTH = SCREEN_WIDTH * 0.2
GO_TO_JAIL_HEIGHT = SCREEN_HEIGHT * 0.14

# --- IN JAIL INFORMATION ---

# in jail window
IN_JAIL_WIN_X = SCREEN_WIDTH * 0.3
IN_JAIL_WIN_Y = SCREEN_HEIGHT * 0.2 
IN_JAIL_WIN_WIDTH = SCREEN_WIDTH * .4
IN_JAIL_WIN_HEIGHT = SCREEN_HEIGHT * .35

# jail text
JAIL_TXT_X = SCREEN_WIDTH * 0.5
JAIL_TXT_Y = SCREEN_HEIGHT * 0.35

# pay button
PAY_BTN_WIDTH = SCREEN_WIDTH * 0.08
PAY_BTN_HEIGHT = SCREEN_HEIGHT * 0.05


# --- GAME BUTTONS ---

#Next Turn Button
NXT_TURN_BTN_X = SCREEN_WIDTH * 0.05
NXT_TURN_BTN_Y = SCREEN_HEIGHT * 0.95
NXT_TURN_BTN_WIDTH = SCREEN_WIDTH * 0.08
NXT_TURN_BTN_HEIGHT = SCREEN_HEIGHT * 0.05

#Buy Button
BUY_BTN_X = SCREEN_WIDTH * 0.45
BUY_BTN_Y = SCREEN_HEIGHT * 0.75
BUY_BTN_WIDTH = SCREEN_WIDTH * 0.06
BUY_BTN_HEIGHT = SCREEN_HEIGHT * 0.05

#Auction Button
AUCT_BTN_X = SCREEN_WIDTH * 0.55
AUCT_BTN_Y = SCREEN_HEIGHT * 0.75
AUCT_BTN_WIDTH = SCREEN_WIDTH * 0.08
AUCT_BTN_HEIGHT = SCREEN_HEIGHT * 0.05

#Ok Button
OK_BTN_X = SCREEN_WIDTH * 0.5
OK_BTN_Y = SCREEN_HEIGHT * 0.75
OK_BTN_WIDTH = SCREEN_WIDTH * 0.06
OK_BTN_HEIGHT = SCREEN_HEIGHT * 0.05


# --- PLAYER BANNER INFORMATION ---

# width and height info
BANNER_WIDTH = SCREEN_WIDTH * 0.19
BANNER_HEIGHT = SCREEN_HEIGHT * 0.12

# background coords
P1_BANNER_X = SCREEN_WIDTH - BANNER_WIDTH 
P1_BANNER_Y = SCREEN_HEIGHT * 0.05

P2_BANNER_X = SCREEN_WIDTH - BANNER_WIDTH 
P2_BANNER_Y = SCREEN_HEIGHT * 0.25

P3_BANNER_X = SCREEN_WIDTH - BANNER_WIDTH 
P3_BANNER_Y = SCREEN_HEIGHT * 0.45

P4_BANNER_X = SCREEN_WIDTH - BANNER_WIDTH 
P4_BANNER_Y = SCREEN_HEIGHT * 0.65

# name coords 
P1_NAME_X = SCREEN_WIDTH
P1_NAME_Y = SCREEN_HEIGHT * 0.08

P2_NAME_X = SCREEN_WIDTH
P2_NAME_Y = SCREEN_HEIGHT * 0.28

P3_NAME_X = SCREEN_WIDTH
P3_NAME_Y = SCREEN_HEIGHT * 0.48

P4_NAME_X = SCREEN_WIDTH
P4_NAME_Y = SCREEN_HEIGHT * 0.68

# money coords
P1_MON_X = SCREEN_WIDTH
P1_MON_Y = SCREEN_HEIGHT * 0.14

P2_MON_X = SCREEN_WIDTH
P2_MON_Y = SCREEN_HEIGHT * 0.34

P3_MON_X = SCREEN_WIDTH
P3_MON_Y = SCREEN_HEIGHT * 0.54

P4_MON_X = SCREEN_WIDTH
P4_MON_Y = SCREEN_HEIGHT * 0.74

# piece coords 
P1_PIECE_X = SCREEN_WIDTH - BANNER_WIDTH
P1_PIECE_Y = SCREEN_HEIGHT * .16

P2_PIECE_X = SCREEN_WIDTH - BANNER_WIDTH
P2_PIECE_Y = SCREEN_HEIGHT * .36

P3_PIECE_X = SCREEN_WIDTH - BANNER_WIDTH
P3_PIECE_Y = SCREEN_HEIGHT * .56

P4_PIECE_X = SCREEN_WIDTH - BANNER_WIDTH
P4_PIECE_Y = SCREEN_HEIGHT * .76

# offset for pieces at startup selection
PIECE_OFFSET = BANNER_WIDTH // 14


# --- PLAYER PROPERTY TAG INFORMATION ---

# width and height info
PROP_TAG_WIDTH = SCREEN_WIDTH * 0.04
PROP_TAG_HEIGHT = SCREEN_HEIGHT * 0.018

# --- AUCTION WINDOW INFORMATION ---

#Buttons

#Dimensions
AUC_BTN_WIDTH = SCREEN_WIDTH * 0.1
AUC_BTN_HEIGHT = SCREEN_HEIGHT * 0.07

BID_BTN_X = SCREEN_WIDTH * 0.42
BID_BTN_Y = SCREEN_HEIGHT * 0.7

WITHDRAW_BTN_X = SCREEN_WIDTH * 0.58
WITHDRAW_BTN_Y = SCREEN_HEIGHT * 0.7

PLAYER_BID_X = SCREEN_WIDTH * 0.4
PLAYER_BID_Y = SCREEN_HEIGHT * 0.37

AUC_CARD_X = SCREEN_WIDTH * 0.54
AUC_CARD_Y = SCREEN_HEIGHT * 0.37

AUC_CARD_WIDTH = SCREEN_WIDTH * 0.12
AUC_CARD_HEIGHT = SCREEN_HEIGHT * 0.26

AUC_CARD_NAME_X = SCREEN_WIDTH * 0.06
AUC_CARD_NAME_Y = SCREEN_HEIGHT * 0.02

AUC_NAME_LINE_START = (SCREEN_WIDTH * 0.44, SCREEN_HEIGHT * 0.33)
AUC_NAME_LINE_END = (SCREEN_WIDTH * 0.56, SCREEN_HEIGHT * 0.33)

AUC_CARD_PRICE_X = SCREEN_WIDTH * 0.06
AUC_CARD_PRICE_Y = SCREEN_HEIGHT * 0.06

AUC_TURN_IND_RAD = SCREEN_WIDTH * 0.015
AUC_TURN_IND_WIDTH = SCREEN_WIDTH * 0.02
AUC_TURN_IND_OFFSET  = SCREEN_WIDTH * 0.1

ASKING_BID_X = SCREEN_WIDTH * 0.65
ASKING_BID_Y = SCREEN_HEIGHT * 0.3

SMALL_CARD_LINE_START = (SCREEN_WIDTH * 0.56, SCREEN_HEIGHT * 0.41)  
SMALL_CARD_LINE_END = (SCREEN_WIDTH * 0.64, SCREEN_HEIGHT * 0.41)

# --- HOUSE BUILDING INFORMATION ---
ACTIVATE_BTN_X = SCREEN_WIDTH * 0.05
ACTIVATE_BTN_Y = SCREEN_HEIGHT * 0.25
ACTIVATE_BTN_WIDTH = SCREEN_WIDTH * 0.1
ACTIVATE_BTN_HEIGHT = SCREEN_HEIGHT * 0.1

BUILD_LABEL_X = SCREEN_WIDTH * 0.049
BUILD_LABEL_Y = SCREEN_HEIGHT * 0.3

CLOSE_BTN_X = SCREEN_WIDTH * 0.7
CLOSE_BTN_Y = SCREEN_HEIGHT * 0.72
CLOSE_BTN_WIDTH = SCREEN_WIDTH * 0.06
CLOSE_BTN_HEIGHT = SCREEN_HEIGHT * 0.04

BUILD_NAME_LINE_START = (SCREEN_WIDTH * 0.4, SCREEN_HEIGHT * 0.33)
BUILD_NAME_LINE_END = (SCREEN_WIDTH * 0.6, SCREEN_HEIGHT * 0.33)


BUILD_PROP_X1 = SCREEN_WIDTH * 0.35
BUILD_PROP_X_OFFSET = SCREEN_WIDTH * 0.25
BUILD_PROP_X2 = BUILD_PROP_X1 + BUILD_PROP_X_OFFSET

BUILD_PROP_Y = SCREEN_HEIGHT * 0.37

BUILD_PROP_OFFSET = SCREEN_WIDTH * 0.027

COLOR_BACKGROUND_X1 = SCREEN_WIDTH * 0.27
COLOR_BACKGROUND_X_OFFSET = SCREEN_WIDTH * 0.05
COLOR_BACKGROUND_X2 = COLOR_BACKGROUND_X1 + COLOR_BACKGROUND_X_OFFSET

COLOR_BACKGROUND_Y = SCREEN_HEIGHT * 0.355
COLOR_BACKGROUND_WIDTH = SCREEN_WIDTH * 0.16
COLOR_BACKGROUND_HEIGHT = SCREEN_HEIGHT * 0.03

COLOR_BACKGROUND_OFFSET = SCREEN_WIDTH * 0.027

BUILD_BTN_X1 = SCREEN_WIDTH * 0.45
BUILD_BTN_X_OFFSET = SCREEN_WIDTH * 0.23
BUILD_BTN_X2 = BUILD_BTN_X1 + BUILD_BTN_X_OFFSET

BUILD_BTN_Y = BUILD_PROP_Y
BUILD_BTN_WIDTH = SCREEN_WIDTH * 0.017
BUILD_BTN_HEIGHT = SCREEN_HEIGHT * 0.029

MIN_BTN_OFFSET = SCREEN_WIDTH * 0.03

# --- HOUSE INFORMATION ---
BUILD_HOUSE_WIDTH = SCREEN_WIDTH * 0.01
BUILD_HOUSE_HEIGHT = SCREEN_HEIGHT * 0.015

BUILD_HOUSE_OFFSET = SCREEN_WIDTH * 0.0115

BUILD_HOTEL_WIDTH = SCREEN_WIDTH * 0.02
BUILD_HOTEL_HEIGHT = SCREEN_HEIGHT * 0.015

BUILD_HOTEL_OFFSET = SCREEN_WIDTH * 0.012